### PR TITLE
Always assume Linux for host OS

### LINKED ISSUE #534: Consider default platform selections, windows/amd64 may not be the best default on Windows
The Image v4 resource defaults to, `platform: "windows/amd64"` on Windows assuming #535 is fixed, resulting in errors when building. The default platform behavior of the Docker daemon seems correct when `platform: ""` (the empty string).

The default behavior here may be the correct one, though we ought to investigate what macOS platforms perform here and what default is best there.

Given the same program as in #535:

```yaml
name: image-yaml
description: A Docker image build
runtime: yaml
config: {}
variables: {}
resources:
  demo-image:
    type: docker:Image
    properties:
      imageName: username/image:tag1
      skipPush: true
      build:
        context: ./app
        platform: windows/amd64 # assuming this became the new default
    options:
      version: v4.0.0
outputs:
  imageName: ${demo-image.imageName}
```

With this Dockerfile:

```Dockerfile
FROM busybox:latest

COPY test.txt /

CMD ["cat", "test.txt"]
```

Results in this error:

```
error: failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:c118f538365369207c12e5794c3cbfb7b042d950af590ae6c287ede74f29b7d4: not found
error: update failed
```

### PR DESCRIPTION
**Pull request by guineveresaenger**
It turns out even Windows builds for Linux by default when using Docker.
This PR leaves the logic for architecture, but defaults to use Linux as the platform OS.

Fixes #534

### CODE REVIEW

File: provider/provider.go [hunk 1]
```diff
@@ -125,12 +125,8 @@ func (p *dockerNativeProvider) Check(ctx context.Context, req *rpc.CheckRequest)
...
-	// Get the system platform
-	os := runtime.GOOS
-	// Docker for Mac builds and runs for linux/amd64, not darwin
-	if os == "darwin" {
-		os = "linux"
-	}
+	// OS defaults to Linux in all cases
+	os := "linux"
 	arch := runtime.GOARCH
 	hostPlatform := os + "/" + arch
```
Comment (AaronFriel) [inline provider/provider.go:131]: I wonder if we could peek into the `moby/moby` repo or `docker/cli` and see what their logic is. If they infer a platform value, should we import their method?

**Review by AaronFriel — APPROVED** [review]
This LGTM, I would not want to spend too much time diving into the Docker CLI.

File: provider/provider.go (hunk 1 above)
Comment (guineveresaenger) [reply provider/provider.go:131]: Ah! I did verify that on macOS with an empty `platform` string, the daemon does assume reasonable OS defaults, i.e. linux on macOS.
