### PR TITLE
Fixes #640

### LINKED ISSUE #640: [csharp] unable to create explicit docker provider
### What happened?

When creating an explicit docker provider in csharp, the program panics.

### Expected Behavior

Create an explicit docker provider.

### Steps to reproduce

1. `pulumi new csharp`
2. `dotnet add package Pulumi.Docker`
3. Execute the below program

```csharp
using System.Collections.Generic;
using Pulumi;

return await Deployment.RunAsync(() =>
{
   var provider = new Pulumi.Docker.Provider("docker", new Pulumi.Docker.ProviderArgs
   {
      Host = "host",
      RegistryAuth = new List<Pulumi.Docker.Inputs.ProviderRegistryAuthArgs>
      {
         new Pulumi.Docker.Inputs.ProviderRegistryAuthArgs
         {
            Address = "",
            Username = "",
            Password = ""
         }
      }
   });

   return new Dictionary<string, object?>
   {
      ["outputKey"] = "outputValue"
   };
});

```

### Output of `pulumi about`

Version      3.67.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME    VERSION
docker  4.2.0
dotnet  unknown

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by t0yv0**
Fixes #640

Requires https://github.com/pulumi/pulumi-terraform-bridge/pull/1140 applied the bridge.

### CODE REVIEW

File: examples/examples_dotnet_test.go [hunk 1]
```diff
@@ -129,6 +134,36 @@ func TestSecretsInExplicitProvider(t *testing.T) {
 		Dir:         path.Join(getCwd(t), "test-secrets-in-explicit-provider", "csharp"),
 		Quick:       true,
 		SkipRefresh: true,
+
+		ExtraRuntimeValidation: func(t *testing.T, stack integration.RuntimeValidationStackInfo) {
+			deploymentJSON, err := json.MarshalIndent(stack.Deployment, "", "  ")
+			assert.NoError(t, err)
+
+			t.Run("program-initiated secrets are encrypted", func(t *testing.T) {
+				t.Skip("TODO <ticket>")
```
Comment (t0yv0) [inline examples/examples_dotnet_test.go:143]: This is still a problem. All these secrets leak into the statefile. We need to ticket and find a fix strategy, unclear if this should go back to the bridge or we can fix the .NET SDK gen; might need to think this through and cross-test with TypeScript SDK gen.

File: provider/hybrid.go [hunk 2]
```diff
@@ -85,6 +82,9 @@ func (dp dockerHybridProvider) Configure(
 
 	// For the most part delegate Configure handling to the bridged provider.
 	resp, err := dp.bridgedProvider.Configure(ctx, request)
+	if err != nil {
+		return nil, err
+	}
```
Comment (t0yv0) [inline provider/hybrid.go:87]: I've overlooked potential panic in reps.SupportsPreview below if err is non-nil. This now prevents such a panic.

File: provider/hybrid.go [hunk 3]
```diff
@@ -56,16 +56,13 @@ func (dp dockerHybridProvider) GetSchema(ctx context.Context, request *rpc.GetSc
 }
 
 func (dp dockerHybridProvider) CheckConfig(ctx context.Context, request *rpc.CheckRequest) (*rpc.CheckResponse, error) {
-	return &rpc.CheckResponse{Inputs: request.GetNews()}, nil
+	// Delegate to the bridged provider, as native Provider does not implement it.
+	return dp.bridgedProvider.CheckConfig(ctx, request)
```
Comment (t0yv0) [inline provider/hybrid.go:60]: This might have some consequences.. Since the Docker provider was written the bridge has re-enabled CheckConfig and it's really important that it gets called, as it cooperates with the Configure implementation on the bridged provider. This is a change in behavior though to enable it as it activates preconfigure callbacks if any and TF-level validators for the provider.

Comment (t0yv0) [reply provider/hybrid.go:60]: It's needed for the fix since CheckConfig does the JSON secrets transcoding as well.

**Review by aq17 — APPROVED** [review]

File: examples/test-secrets-in-explicit-provider/csharp/Program.cs [hunk 4]
```diff
@@ -1,24 +1,62 @@
...
+
+using Pulumi;
+using Pulumi.Random;
 
 return await Deployment.RunAsync(() =>
 {
-   var provider = new Pulumi.Docker.Provider("docker", new Pulumi.Docker.ProviderArgs
+
+   // Test passing values marked secret by the user program to the provider.
+   var provider1 = new Pulumi.Docker.Provider("provider-with-sensitive-address", new Pulumi.Docker.ProviderArgs
```
Comment (guineveresaenger) [inline examples/test-secrets-in-explicit-provider/csharp/Program.cs:12]: Which of these providers are currently needing to be skipped in testing? it might be useful to have separate pulumi programs for each, but if the failed test output makes it clear then I see no need.

**Review by guineveresaenger — COMMENTED** [review]
I'd like to know a bit more about what "program-initiated" secrets are in this case, and of course, we should file a followup issue for this.
