### PR TITLE
Explicitly read in SSH config flags to the docker client configuration

### LINKED ISSUE #702: Resource type `Provider` does not seem to respect `sshOpts` anymore
### What happened?

I'm trying to connect to Docker on a remote host by using SSH. When using the `sshOpts` property of the `Provider` resource type to pass a user name and SSH private key file, the arguments are not passed to the SSH command line it seems.

### Expected Behavior

The `sshOpts` should be passed as arguments when using SSH.

### Steps to reproduce

I'm using the following config:
```typescript
const provider = new docker.Provider("docker-provider", {
    host: pulumi.interpolate`ssh://${server.ipv4Address}`,
    sshOpts: [
        "-l", "docker",
        "-i", "private-key",
        "-o", "StrictHostKeyChecking=no",
        "-o", "UserKnownHostsFile=/dev/null"
    ],
});

const remoteImage = new docker.RemoteImage("image", {
    name: "ubuntu:latest"
}, {
    provider: provider
});

const container = new docker.Container("container", {
    image: remoteImage.imageId
}, {
    provider: provider
});
```

This fails with
```
Diagnostics:
  docker:index:RemoteImage (image):
    error: Docker native provider returned an unexpected error from Configure: error during connect: Get "http://docker.example.com/v1.24/plugins": command [ssh -- 123.45.67.89 docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
    Host key verification failed.
```
because the private key file is not used. I can connect fine when calling `ssh` manually with said arguments.

The `sshOpts` are not displayed as part of the `command [ssh - ...]` line which is why I assume they are not passed when trying to establish the connection. In earlier versions I could see the arguments as part of this line when I ran into an error.

### Output of `pulumi about`

```
CLI
Version      3.76.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
docker  4.3.1
hcloud  1.14.0
nodejs  unknown
tls     4.10.0

Host
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/home/linuxbrew/.linuxbrew/bin/node' version='v20.4.0'

Current Stack: <xxx>/test/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/<xxx>
User           <xxx>
Organizations  <xxx>

Dependencies:
NAME            VERSION
@pulumi/docker  4.3.1
@pulumi/hcloud  1.14.0
@pulumi/pulumi  3.76.1
@pulumi/tls     4.10.0
@types/node     16.18.39

Pulumi locates its logs in /tmp by default
```

### Additional context

This has worked fine in version 3.6.1 of the provider, but is not working in the current 4.3.1 release.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by guineveresaenger**
Pulumirpc's req.GetVariables flattens the configs into strings, even though `sshOpts` is properly a slice of strings. Worse, we get all sorts of extra escape characters. 

This pull request unmarshals `sshOpts` when needed and passes the resulting ssh flag options to the SSH connection helper.

Additionally, we set up a TS test for a remote Docker host using a Digitalocean Docker Droplet.

To make this work, there are some changes to the acceptance tests Workflow as well. This PR will need a followup in ci-mgmt to incorporate these changes properly.

This PR needs follow-up changes to ci-mgmt to 

Fixes #702.

- Read in SSH flags to the connection helper to avoid error in Configure
- Add integration test for SSH connections

### CODE REVIEW

File: provider/image.go [hunk 1]
```diff
@@ -942,3 +943,16 @@ func mapDockerignore(dockerfile string) string {
...
+	trimmedOpts := strings.Trim(sshOptsFromConf, "[]")
+	slicedOpts := strings.Split(trimmedOpts, ",")
+	sshopts := []string{}
+
+	for _, val := range slicedOpts {
+		val = strings.ReplaceAll(val, "\"", "")
+		sshopts = append(sshopts, val)
+	}
+	return sshopts
+}
```
Comment (iwahbe) [inline provider/image.go:958]: I believe that we just encode this into JSON. I think we should just decode it as json as well (`json.Unmarshal`). I'm not sure how this works with computed values in provider inputs.

**Review by iwahbe — CHANGES_REQUESTED** [review]
I think we can do this without writing a custom unmarshal function. In any case, I would like to see a GRPC or integration level test here, not just a test of `SSHOptsToSlice` directly.

At the very least, this will do the wrong thing when given untyped input (as is done by JS). We should error in that case.

File: provider/image.go [hunk 2]
```diff
@@ -849,8 +850,14 @@ func configureDockerClientInner(configs map[string]string, host string) (*client
 	} else {
 		// No TLS certificate material provided, create an http client
 		if host != "" {
+			var sshopts []string
+			if opts, ok := configs["sshOpts]"]; ok {
```
Comment (iwahbe) [inline provider/image.go:854]: Typo?
```suggestion
			if opts, ok := configs["sshOpts"]; ok {
```

File: examples/test-ssh-conn/ts/index.ts [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+        "-o", "StrictHostKeyChecking=no",
+        "-o", "UserKnownHostsFile=/dev/null"
+    ],
+});
+
+const remoteImage = new docker.RemoteImage("image", {
+    name: "nginx"
+}, {
+    provider: provider
+});
```
Comment (iwahbe) [inline examples/test-ssh-conn/ts/index.ts:39]: Nit:
```suggestion
}, { provider });
```

File: examples/test-ssh-conn/ts/index.ts [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+    return new Promise(resolve => setTimeout(resolve, ms));
+}
+async function addSleep(addr: string, ms: number) {
+    console.log("Sleeping...")
+    await sleep(ms)
+    console.log("Done Sleeping")
+    return addr
+}
+
+let ip = remoteHost.ipv4Address.apply(ipv4Address => addSleep(ipv4Address, 20000))
```
Comment (iwahbe) [inline examples/test-ssh-conn/ts/index.ts:22]:
```suggestion
const ip = remoteHost.ipv4Address.apply(ipv4Address => addSleep(ipv4Address, 20000))
```

File: examples/examples_nodejs_test.go [hunk 5]
```diff
@@ -196,6 +197,32 @@ func TestSecretsInExplicitProviderNode(t *testing.T) {
 	integration.ProgramTest(t, &test)
 }
 
+func TestSSHConnNode(t *testing.T) {
+	token := os.Getenv("DIGITALOCEAN_TOKEN")
+	if token == "" {
+		t.Skipf("Skipping test due to missing DIGITALOCEAN_TOKEN environment variable")
+	}
```
Comment (iwahbe) [inline examples/examples_nodejs_test.go:204]: This has bit us in the past. Will `token` ever be `""` in CI? If not, lets prevent skipping in CI.

File: examples/examples_nodejs_test.go [hunk 6]
```diff
@@ -196,6 +197,32 @@ func TestSecretsInExplicitProviderNode(t *testing.T) {
...
+	test := getJsOptions(t).
+		With(integration.ProgramTestOptions{
+			Dir: path.Join(getCwd(t), "test-ssh-conn", "ts"),
+			ExtraRuntimeValidation: func(t *testing.T, stack integration.RuntimeValidationStackInfo) {
+				ipOutput, ok := stack.Outputs["ipOutput"]
+				assert.True(t, ok)
+				assert.NotEmpty(t, ipOutput)
+				// Due to a bug in the docker client, we add sleep here so our SSH connection does not get refused.
+				time.Sleep(20 * time.Second)
```
Comment (iwahbe) [inline examples/examples_nodejs_test.go:213]: I'm really confused here. Is the goal to pause between each `pulumi up`? I'm concerned that we are relying on the implementation details of `integration.ProgramTest` here. They could always decide to run `ExtraRuntimeValidation` in another thread.

If this is a known bug, is there an associated issue you can link to?

File: .github/workflows/run-acceptance-tests.yml [hunk 7]
```diff
@@ -388,6 +389,10 @@ jobs:
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         version: v2.4.0
+    - name: Setup SSH key
+      uses: webfactory/ssh-agent@v0.7.0
+      with:
+        ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY_FOR_DIGITALOCEAN }}
```
Comment (iwahbe) [inline .github/workflows/run-acceptance-tests.yml:395]: Won't this be overriden by ci-mgmt?

**Review by iwahbe — COMMENTED** [review]
I really appreciate the README.md for the test. Thats awesome!

File: .github/workflows/run-acceptance-tests.yml (hunk 7 above)
Comment (thomas11) [reply .github/workflows/run-acceptance-tests.yml:395]: True. Addressed by pulumi/ci-mgmt#517.

File: examples/examples_nodejs_test.go (hunk 6 above)
Comment (thomas11) [reply examples/examples_nodejs_test.go]: It seems that the actual TS test also has a 20s sleep, so I removed this one.

File: examples/examples_nodejs_test.go (hunk 5 above)
Comment (thomas11) [reply examples/examples_nodejs_test.go:205]: I agree. However, this is outside the scope of this PR since other tests do this already, and other providers, too.

File: provider/image.go [hunk 8]
```diff
@@ -849,8 +850,14 @@ func configureDockerClientInner(configs map[string]string, host string) (*client
 	} else {
 		// No TLS certificate material provided, create an http client
 		if host != "" {
+			var sshopts []string
+			if opts, ok := configs["sshOpts"]; ok {
+				err = json.Unmarshal([]byte(opts), &sshopts)
```
Comment (iwahbe) [inline provider/image.go:855]: Nit: This keeps variables local.
```suggestion
				err := json.Unmarshal([]byte(opts), &sshopts)
```

File: examples/examples_dotnet_test.go [hunk 9]
```diff
@@ -82,6 +82,8 @@ func TestAwsContainerRegistryDotnet(t *testing.T) {
 }
 
 func TestDigitaloceanContainerRegistryDotnet(t *testing.T) {
+	t.Skipf("Skipping test due to known storageUsageBytes issue #718")
```
Comment (iwahbe) [inline examples/examples_dotnet_test.go:85]: Nit: Can this be a link?

File: examples/digitalocean-container-registry/csharp/Program.cs [hunk 10]
```diff
@@ -52,15 +52,16 @@ class Program
...
-            Build = new Pulumi.Docker.Inputs.DockerBuildArgs { Context = "app" },
+            Build = new DockerBuildArgs { Context = "app" },
             ImageName = imageName,
             Registry = registryInfo,
         });
 
         // Export the resulting base name in addition to the specific version pushed.
-	// Export the resulting image name
-        return new Dictionary<string, object>
+	    // Export the resulting image name
```
Comment (iwahbe) [inline examples/digitalocean-container-registry/csharp/Program.cs:61]: Nit: formatting.
```suggestion
	// Export the resulting image name
```

File: .github/workflows/run-acceptance-tests.yml (hunk 7 above)
Comment (iwahbe) [reply .github/workflows/run-acceptance-tests.yml:395]: I believe this part will still be overriden. All #517 does is set `DIGITALOCEAN_TOKEN`.

**Review by iwahbe — APPROVED** [review]
A couple of nits, but overall looking good. 🚢🚢🚢
