### PR TITLE
Choose between system and user socket for Docker connection

### LINKED ISSUE #619: docker.Image: Cannot connect to the Docker daemon because my socket address is different
### What happened?

When running a simple Pulumi program, I get the following error even though Docker is running:

```text
Diagnostics:
  docker:index:Image (demo-image):
    error: 1 error occurred:
        * Error pinging Docker server: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### Expected Behavior

No error.

### Steps to reproduce

```typescript
const demoImage = new docker.Image("demo-image", {
    build: {
        context: ".",
        dockerfile: "Dockerfile",
    },
    imageName: "username/image:tag1",
    skipPush: true,
});
```

```dockerfile
FROM alpine:3.14
```

### Output of `pulumi about`

```text
CLI          
Version      3.65.1
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.101.0
docker        4.2.0
nodejs        unknown
random        4.13.0

Host     
OS       darwin
Version  13.3.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v19.5.0'

Current Stack: jkodrofftest/test-fix-tempalte/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jkodroff
User           jkodroff
Organizations  jkodroff, jkodrofftest, zephyr, demo, pulumi

Dependencies:
NAME                  VERSION
@pulumi/docker        4.2.0
@pulumi/pulumi        3.65.1
@pulumi/random        4.13.0
@types/node           16.18.25
@pulumi/azure-native  1.101.0

Pulumi locates its logs in /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/ by default

```

### Additional context

Debugged this with @guineveresaenger and @AaronFriel for a while, and we did not come up with an obvious cause. We:

* verified that Docker is definitely running on my machine
* tried a reboot
* grabbed the output of a few Docker commands, no obvious cause
* verified that @guineveresaenger does not see the same issue with this program
* verified that v4.1.x behaves the same
* verified that v3.latest _does not_ exhibit the bug
* tried blowing away my `~/.docker/config.json`, same result
* verified that I do not have `DOCKER_HOME` set (or whatever the env var is)

Some info about my machine:

image

And here's my `docker info` dump:

```text
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.10.0
    Path:     /Users/jkodroff/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.841GiB
 Name: docker-desktop
 ID: d9eba96f-5d82-413d-aa48-776906674f45
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by thomas11**
Docker's default installation on MacOS now puts the Docker daemon in user space. Therefore, the default socket host doesn't work anymore, in both the native and the bridged side of this hybrid provider.

This PR checks whether the default system-wide host works, and if not, tests the user space one. If that one works, we export it as DOCKER_HOST so that the bridged provider uses it, too.

## Testing

```ts
import * as docker from "@pulumi/docker";

const image = new docker.RemoteImage("alpine", {
  name: "alpine:latest"
});

const container = new docker.Container("alpine", {
  image: image.id,
});
```

For this program,
```bash
PATH=/Users/tkappler/pulumi/pulumi-docker/bin:$PATH pulumi preview
```
works both with the Docker setting "Allow the default Docker socket to be used" on and off (with restart in between changes).

The unit tests are a little uglier now because we don't want to test the connection from them.

Fixes #619

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -106,7 +106,7 @@ provider: tfgen install_plugins
 test:
 	cd examples && go test -v -tags=all -parallel $(TESTPARALLELISM) -timeout 2h
 
-tfgen: install_plugins upstream docs
```
Comment (mikhailshilkov) [inline Makefile:109]: Probably not intended to commit?

File: provider/pkg/version/version.go [hunk 2]
```diff
@@ -15,4 +15,4 @@
 package version
 
 // Version is initialized by the Go linker to contain the semver of this build.
-var Version string
+var Version string = "v4.3.0"
```
Comment (mikhailshilkov) [inline provider/pkg/version/version.go:18]: Does this need to be here?

File: provider/image.go [hunk 3]
```diff
@@ -741,9 +744,45 @@ func processLogLine(msg string) (string, error) {
 	return info, nil
 }
 
-func configureDockerClient(configs map[string]string) (*client.Client, error) {
+// When `verify` is set, this function will check that the connection to the docker daemon works.
+// If it doesn't and no host was configured, it will try to connect to the user's docker daemon.
+func configureDockerClient(configs map[string]string, verify bool) (*client.Client, error) {
```
Comment (mikhailshilkov) [inline provider/image.go:749]: Do we need to add an (integration?) test to check the `verify=true` path?

File: provider/image.go [hunk 4]
```diff
@@ -21,6 +19,10 @@ import (
 	"strings"
 	"time"
 
+	"github.com/docker/cli/cli/connhelper"
+	"github.com/moby/buildkit/session"
+	"github.com/moby/buildkit/session/auth/authprovider"
+
```
Comment (iwahbe) [inline provider/image.go:25]: There shouldn't be a space here. It should be part of the block below it.

File: provider/image.go (hunk 3 above)
Comment (iwahbe) [inline provider/image.go:749]: We only call `configureDockerClient(config, true)` in production. We never call with `verify=false` except in testing. Can we simply remove the `verify` parameter?

This will ensure that we test the code path we care about *and* will reduce complexity.

Comment (thomas11) [reply provider/image.go:749]: I introduced `verify=false` _for_ testing. In unit tests, we cannot verify connections because they don't actually exist.

An alternative would be to extract relevant parts into interface and mock it for tests. Probably cleaner but pretty involved.

Comment (thomas11) [reply provider/image.go:748]: The integration tests in `/examples` use the actual provider and therefore `verify=true`, as called from `Configure`.

Comment (iwahbe) [reply provider/image.go:748]: If thats the case, I would love a comment saying:
> `verify` is a testing affordance, and will always be `true` in production.

It seems like we can move the tests from `configureDockerClient` to `configureDockerClientInner` will little work and remove the extra parameter.

I leave it up to you whether to add the comment or change the test target.

**Review by iwahbe — APPROVED** [review]
1 nit to address. After that, LGTM!

File: provider/image.go [hunk 5]
```diff
@@ -756,88 +797,79 @@ func configureDockerClient(configs map[string]string) (*client.Client, error) {
 	if val, ok := configs["certPath"]; ok {
 		certPath = val
 	}
-	if val, ok := configs["host"]; ok {
-		host = val
-	}
+
+	var err error
```
Comment (guineveresaenger) [inline provider/image.go:801]: (nit) do we need this explicit declaration? It looks like all instances in the context are assigned via `:=`, unless I missed something.

File: provider/image.go [hunk 6]
```diff
@@ -756,88 +797,79 @@ func configureDockerClient(configs map[string]string) (*client.Client, error) {
...
+	clientOpts := []client.Opt{}
```
Comment (guineveresaenger) [inline provider/image.go:802]: my sincerest thanks for cleaning this up!

File: provider/provider.go [hunk 7]
```diff
@@ -80,6 +81,18 @@ func (p *dockerNativeProvider) Configure(_ context.Context, req *rpc.ConfigureRe
 	for key, val := range config {
 		p.config[key] = val
 	}
+
+	// Configure a Docker daemon client here even though we won't use it. We want use the native
+	// provider's logic to determine the host address and then set the DOCKER_HOST environment
+	// accordingly so the bridged provider picks it up, too.
```
Comment (guineveresaenger) [inline provider/provider.go:87]: I see - we're using `configureDockerClient` to explicitly set the `DOCKER_HOST` env var.

In the case where the docker host is set via provider config (not env var), `DOCKER_HOST` would then be set to that value, and they would be the same, creating a failsafe.

I'm not super excited about "borrowing" logic from the native provider in this way - truly this should be a (solved) upstream problem (or we should implement the docker host config logic on the hybrid level), but it seems safe, and the early configure failure is certainly nice.

**Review by guineveresaenger — APPROVED** [review]

File: provider/provider.go (hunk 7 above)
Comment (thomas11) [reply provider/provider.go:87]: I expect that as more people run into the issue with the upstream provider, it'll eventually get fixed there.
