### PR TITLE
Use fsutil.Walk() to compute context digest

### LINKED ISSUE #607: New .dockerignore pattern matcher is under-ignoring
### What happened?

I have the following folder structure:

```
projects/services/src
projects/api/src
projects/infrastructure/src
```

And then inside each project I have a `.venv` folder containing my Python dependencies:
```
projects/services/.venv
projects/api/.venv
projects/infrastructure/.venv
```

My .dockerignore is like this:
```
# Ignore everything
*

# Except these
!pyproject.toml
!poetry.lock

!projects/*/src
```

When I run `pulumi up`, I get the following error:
```
Diagnostics:
  docker:index:Image (services):
    error: unable to hash build context: open /workspace/py/projects/infrastructure/.venv/lib/python3.10/site-packages/IPython: no such file or directory
```

(My context and Dockerfile are both in /workspace/py)

### Expected Behavior

When I run `docker buildx build ...` then the image is built just fine, and if I explore inside with bash I can navigate that the correct files are there (and only those)

The `.venv` shouldn't even be considered by the hashing function, as it's ignored by the very first pattern `*`

### Steps to reproduce

I think we need a unit test for a more complex monorepo structure, because there's still some discrepancy between Docker's context hash and Pulumi's

### Output of `pulumi about`

CLI          
Version      3.64.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME       VERSION
aws        5.37.0
awsx       1.0.2
docker     4.2.0
python     unknown
random     4.13.0
snowflake  0.23.0

Host     
OS       debian
Version  11.6
Arch     aarch64

This project is written in python: executable='/usr/local/python/current/bin/python3' version='3.10.10

### Additional context

@guineveresaenger @AaronFriel this might be connected to the 4.2.0 release and your recent PR (https://github.com/pulumi/pulumi-docker/pull/595)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by AaronFriel**
This removes the `patternmatcher` library and replaces our context walk with the same library as used in Buildkit.

It turns out we *may* have already fixed #607 in #596, as the tests pass without changes to `provider.go`. However, there is logic in `fsutil.Walk()` absent in our previous implementation and it makes sense to limit the scope of the provider to reusing the routine from the `fsutil` library.

Fixes #607

### CODE REVIEW

File: provider/provider.go [hunk 1]
```diff
@@ -544,38 +540,16 @@ func hashContext(dockerContextPath string, dockerfile string) (string, error) {
...
-	err = filepath.WalkDir(dockerContextPath, func(path string, d os.DirEntry, err error) error {
-		if err != nil {
-			return err
-		}
-		// The relative path is used in checking against .dockerignore and what is used in computing the
-		// name of the file hashed.
-		relPath, err := filepath.Rel(dockerContextPath, path)
+	err = fsutil.Walk(context.Background(), dockerContextPath, &fsutil.WalkOpt{
+		ExcludePatterns: ignorePatterns,
+	}, func(relPath string, d fs.FileInfo, err error) error {
```
Comment (guineveresaenger) [inline provider/provider.go:545]: I'd like to disambiguate these vars a bit - relPath gets me thinking about relative dockerfiles! 
```suggestion
	}, func(filePath string, fileInfo fs.FileInfo, err error) error {
```

**Review by guineveresaenger — APPROVED** [review]
The line length linter is complaining, and I have some nits about var names.

Note we are still using the `patternmatcher` library as an indirect dependency - Walk() calls it when handling the ignore options. (this is fine obviously, just a point of clarity)

**Review by guineveresaenger — APPROVED** [review]
LGTM! Thank you!
