### PR TITLE
Image: Unwrap Secrets at RPC function level

### LINKED ISSUE #587: Image Build Args containing a secret output causes panic: "interface conversion: interface {} is resource.Computed, not resource.PropertyMap"
### What happened?

A panic occurs when building a docker image, where the Build.Args InputMap contains an entry with a secret output:

```pulumi:pulumi:Stack (docker-test-dev2):
    panic: interface conversion: interface {} is *resource.Secret, not resource.PropertyMap
    goroutine 85 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/resource.PropertyValue.ObjectValue(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/go/common/resource/properties.go:431
    github.com/pulumi/pulumi-docker/provider/v4.marshalArgs({{0x1585a80?, 0xc0007eee30?}})
        /home/runner/work/pulumi-docker/pulumi-docker/provider/image.go:467 +0x217
    github.com/pulumi/pulumi-docker/provider/v4.marshalBuildAndApplyDefaults({{0x179f480?, 0xc0002f4840?}})
        /home/runner/work/pulumi-docker/pulumi-docker/provider/image.go:397 +0x245
    github.com/pulumi/pulumi-docker/provider/v4.(*dockerNativeProvider).Check(0xc0006add10, {0x1a8bb68, 0xc0002f47e0}, 0xc000398c60)
        /home/runner/work/pulumi-docker/pulumi-docker/provider/provider.go:120 +0x205
    github.com/pulumi/pulumi-docker/provider/v4.dockerHybridProvider.Check({{}, {0x245c620, 0x25e12, 0x25e12}, {0x1a770a4, 0x6}, {0x1a981f0, 0xc000672000}, {0x1a98140, 0xc0006add10}}, ...)
        /home/runner/work/pulumi-docker/pulumi-docker/provider/hybrid.go:96 +0xd7
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler.func1({0x1a8bb68, 0xc0002f47e0}, {0x175db00?, 0xc000398c60})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/proto/go/provider_grpc.pb.go:537 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1a8bb68, 0xc0002f42d0}, {0x175db00, 0xc000398c60}, 0xc00058c9c0, 0xc000688ca8)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler({0x17d5520?, 0xc0006470e0}, {0x1a8bb68, 0xc0002f42d0}, 0xc0002e12d0, 0xc00032bec0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/proto/go/provider_grpc.pb.go:539 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000836000, {0x1a93e20, 0xc0006944e0}, 0xc0007a05a0, 0xc00032c1b0, 0x24aa650, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336 +0xd33
    google.golang.org/grpc.(*Server).handleStream(0xc000836000, {0x1a93e20, 0xc0006944e0}, 0xc0007a05a0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704 +0xa36
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
```

### Expected Behavior

The image to be created. This scenario worked as expected when using Pulumi.Docker 3.6.1.

### Steps to reproduce

using Pulumi;
using Pulumi.Docker;
using Pulumi.Docker.Inputs;

public class DockerStack : Stack
{
   public DockerStack()
   {
      var connString = Output.CreateSecret("connstring");
      var _ = new Image("test", new ImageArgs
      {
         SkipPush = true,
         ImageName = "hi",
         Build = new DockerBuildArgs
         {
            Context = "./",
            Dockerfile = "Dockerfile",
            Args = {
               {"CONNECTION_STRING", connString},
            },
         }
      });
   }
}

### Output of `pulumi about`

```
CLI
Version      3.62.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME    VERSION
docker  4.1.2
dotnet  unknown

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='7.0.102'

Current Stack: jlewicki-nevo/docker-test/dev2

TYPE                      URN
pulumi:pulumi:Stack       urn:pulumi:dev2::docker-test::pulumi:pulumi:Stack::docker-test-dev2
pulumi:providers:docker   urn:pulumi:dev2::docker-test::pulumi:providers:docker::default_4_1_2
docker:index/image:Image  urn:pulumi:dev2::docker-test::docker:index/image:Image::test


Found no pending operations associated with dev2

Backend
Name           pulumi.com
URL            https://app.pulumi.com/jlewicki-nevo
User           jlewicki-nevo
Organizations  jlewicki-nevo

Dependencies:
NAME           VERSION
Pulumi         3.54.1
Pulumi.Docker  4.1.2

```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by guineveresaenger**
When serializing inputs and outputs into a resource object, we need access to the underlying values of Secrets.
If we set KeepSecrets to true, this may cause a panic in case an input is a * resource.Secret rather than a resource.PropertyMap.
This PR unsets KeepSecrets on all RPC calls to use the default of false. 
This is safe, as we are not returning any sensitive information as Outputs.
Fixes #587.

- Do not keep secrets when unmarshaling inputs
- Remove KeepSecrets as we aren't setting any
- Add integration test to verify secrets do not panic

### CODE REVIEW

File: provider/provider.go [hunk 1]
```diff
@@ -110,7 +110,6 @@ func (p *dockerNativeProvider) Check(ctx context.Context, req *rpc.CheckRequest)
 	inputs, err := plugin.UnmarshalProperties(req.GetNews(), plugin.MarshalOptions{
 		KeepUnknowns: false,
 		SkipNulls:    true,
-		KeepSecrets:  true,
```
Comment (iwahbe) [inline provider/provider.go:113]: It seems like its worth refactoring `plugin.UnmarshalProperties(req.GetNews(), plugin.MarshalOptions{ KeepUnknowns: false, SkipNulls: true })` into `p.unmarshalProperties(req.GetNews())`. with `p.unmarshalProperties` a wrapper function that unifies `MarshalOptions`.

**Review by t0yv0 — APPROVED** [review]
:shipit:

File: provider/provider.go (hunk 1 above)
Comment (iwahbe) [reply provider/provider.go:113]: We create `MarshalOptions` multiple times with largely the same arguments, which we define each time. To keep DRY, we could move the `plugin.UnmarshalProperties` call into a function that itself has the defaults, preventing us from needing to provide them each time at the call-site. 

This is what I did in the go provider SDK:
https://github.com/pulumi/pulumi-go-provider/blob/e8f254577aee9fba48c3a8cf7238ef95a4b14141/provider.go#L584-L599
