### PR TITLE
Fix: docker host connection for SSH

### LINKED ISSUE #706: Remote connection issue via SSH for `RemoteImage` resources in `v4.3.1`
### What happened?

After updating `@pulumi/docker` (npm package) to [`4.3.1`](https://github.com/pulumi/pulumi-docker/releases/tag/v4.3.1) my deployments started to constantly fail attempting to pull images for `RemoteImage` resource on remote server via SSH connection. https://github.com/pulumi/pulumi-docker/pull/697 seem to be responsible for the issue as it is the only change affecting `RemoteImage` resource and it seem to change the way pulumi picks address for `DOCKER_HOST`.

### Expected Behavior

Docker pulls images on remote machine without issues.

### Steps to reproduce

You can find reproduction steps in this repository: https://github.com/octet-stream/pulumi-remote-host-issue
It also includes ready to use pulumi project.

### Output of `pulumi about`

CLI          
Version      3.76.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
docker  4.3.1
docker  4.3.0
nodejs  unknown

Host     
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in nodejs:
version='v20.5.0'

Current Stack: octet-stream/pulumi-remote-host-issue/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/octet-stream
User           octet-stream
Organizations  octet-stream

### Additional context

Current solution is to stick on exact version of pulumi — [`4.3.0`](https://github.com/pulumi/pulumi-docker/releases/tag/v4.3.0)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by guineveresaenger**
In #697, we added logic to Configure to determine and set the docker host address.
Because SSH uses a connection helper, in this PR we check for the connection helper string, and do not re-set DOCKER_HOST.

I verified this fixes the user-provided bug repro submitted with #706.

Fixes #706

### CODE REVIEW

**Comment by guineveresaenger** [comment]
Note: tests are currently failing due to https://github.com/pulumi/pulumi/pull/13676 - once that is available in CI, `make docs` should work again.

File: provider/provider.go [hunk 1]
```diff
@@ -90,8 +90,14 @@ func (p *dockerNativeProvider) Configure(_ context.Context, req *rpc.ConfigureRe
...
 	host := client.DaemonHost()
-	log.Printf("Setting DOCKER_HOST to %s", host)
-	os.Setenv("DOCKER_HOST", host)
+
+	// In the case of a remote docker client that we connect to with SSH, we use a connection helper as the daemon host.
+	// Per the docker/cli/cli/connhelper package, this is hardcoded as http://docker.example.com for SSH.
+	// If we are using a remote host via SSH, we do NOT want to overwrite DOCKER_HOST here.
+	if host != "http://docker.example.com" {
+		log.Printf("Setting DOCKER_HOST to %s", host)
+		os.Setenv("DOCKER_HOST", host)
```
Comment (t0yv0) [inline provider/provider.go:99]: Both before and after the change this is using os.Setenv that has process scope. Is it at all possible to avoid doing os.Setenv and pass the configuration via an API? Or is this necessary?

File: provider/provider.go [hunk 2]
```diff
@@ -90,8 +90,14 @@ func (p *dockerNativeProvider) Configure(_ context.Context, req *rpc.ConfigureRe
 		return nil, err
 	}
 	host := client.DaemonHost()
-	log.Printf("Setting DOCKER_HOST to %s", host)
-	os.Setenv("DOCKER_HOST", host)
+
+	// In the case of a remote docker client that we connect to with SSH, we use a connection helper as the daemon host.
+	// Per the docker/cli/cli/connhelper package, this is hardcoded as http://docker.example.com for SSH.
+	// If we are using a remote host via SSH, we do NOT want to overwrite DOCKER_HOST here.
```
Comment (t0yv0) [inline provider/provider.go:96]: How can we cover this change with a test?

File: provider/provider.go (hunk 1 above)
Comment (guineveresaenger) [reply provider/provider.go:99]: I'm not sure - as I understand it, this option turns up if
- we do not set the host explicitly (i.e. it is passed via env vars)
- if the default host does not succeed, we try the user host
- we set the env var to the host that works, which in the case of an explicitly configured host (passed in via confiv not env) would be the same as in the config file.

I'm wondering if we can set `p.config["host"]` instead? 🤔

File: provider/provider.go (hunk 2 above)
Comment (t0yv0) [reply provider/provider.go:96]: How about a unit test perhaps after factoring the code a bit? Where's the information flowing when you set os.Setenv("DOCKER_HOST", host), what's the code that reads this back, how can we make that connection more obvious?

Comment (t0yv0) [reply provider/provider.go:96]: Poking around the codebase. Why is configureDockerClient is even called in Configure.

I see this comment:

```
	// Configure a Docker daemon client here even though we won't use it. We want use the native
	// provider's logic to determine the host address and then set the DOCKER_HOST environment
	// accordingly so the bridged provider picks it up, too.
```

This is very unfortunate. I see this was introduced in https://github.com/pulumi/pulumi-docker/pull/697/files#diff-0e3b5cd2e6abf4633712dbd2d69307b7fbd75bc71844e34306afdcd9840dab64 with very abbreviated testing also.

I'll ask the team.

Comment (guineveresaenger) [reply provider/provider.go:96]: https://github.com/pulumi/pulumi-docker/issues/710

**Review by t0yv0 — APPROVED** [review]
Per discussion approving to expedite the P1 fix, knowing that an integration test is coming in shortly after to fix the right behavior in-place.
