### PR TITLE
fix: return reasonable errors for cache marshaling and allow for unknowns to pass through

### LINKED ISSUE #576: cache_from when ECR registry doesn't exist causes panic
### What happened?

Trying to deploy a new Pulumi project for the first time.
It defines an AWS ECR Repository, and an `Image`.
The `Image` has `cache_from` set to the ECR repository explicitly. As far as I know, this is necessary if I want the 2nd+ build to be fast.

The ECR Repo does not yet exist. I am _guessing_ this is relevant because I have seen `pulumi-docker` work on existing projects.

`pulumi preview` or `pulumi up` causes a panic!

```
    panic: interface conversion: interface {} is resource.Computed, not string
    goroutine 101 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/resource.PropertyValue.StringValue(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/go/common/resource/properties.go:419
    github.com/pulumi/pulumi-docker/provider/v4.marshalCachedImages({{0x211cf40?, 0xc000420cf0?}})
    	/home/runner/work/pulumi-docker/pulumi-docker/provider/image.go:414 +0x22b
    github.com/pulumi/pulumi-docker/provider/v4.(*dockerNativeProvider).Check(0xc000578b80, {0x24070e8, 0xc000420c90}, 0xc0004222a0)
    	/home/runner/work/pulumi-docker/pulumi-docker/provider/provider.go:194 +0x88d
    github.com/pulumi/pulumi-docker/provider/v4.dockerHybridProvider.Check({{}, {0x2dd8d80, 0x25dfe, 0x25dfe}, {0x23f231c, 0x6}, {0x24136b0, 0xc00022b180}, {0x2413600, 0xc000578b80}}, ...)
    	/home/runner/work/pulumi-docker/pulumi-docker/provider/hybrid.go:96 +0xd7
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler.func1({0x24070e8, 0xc000420c90}, {0x20db800?, 0xc0004222a0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/proto/go/provider_grpc.pb.go:537 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x24070e8, 0xc000420930}, {0x20db800, 0xc0004222a0}, 0xc000876180, 0xc000126690)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler({0x2152be0?, 0xc000790320}, {0x24070e8, 0xc000420930}, 0xc00074e0e0, 0xc000577380)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.56.0/proto/go/provider_grpc.pb.go:539 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000276000, {0x240f360, 0xc00050d040}, 0xc00037eea0, 0xc000792030, 0x2e1a6f0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336 +0xd33
    google.golang.org/grpc.(*Server).handleStream(0xc000276000, {0x240f360, 0xc00050d040}, 0xc00037eea0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704 +0xa36
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

```

If I comment out the `cache_from` line, the panic does not occur.

### Expected Behavior

ECR Repository to be created
No caching can happen on first time
Image to be built
Image to be pushed

### Steps to reproduce

`my_app/deployment/__main__.py`:
```python
import base64
from pathlib import Path

import pulumi
import pulumi_aws as aws
import pulumi_docker as docker

PROJECT_DIR = Path(__file__).resolve().parent.parent


# https://github.com/pulumi/pulumi-docker/blob/master/examples/aws-container-registry/py/__main__.py
# Get registry info (creds and endpoint) so we can build/publish to it.
def _get_registry_info(rid):
    creds = aws.ecr.get_credentials(registry_id=rid)
    decoded = base64.b64decode(creds.authorization_token).decode()
    parts = decoded.split(":")
    if len(parts) != 2:
        raise Exception("Invalid credentials")
    return docker.RegistryArgs(
        server=creds.proxy_endpoint,
        username=parts[0],
        password=parts[1],
    )


ecr_repo = aws.ecr.Repository(
    resource_name="my_app:repo",
    name="my_app",
)

registry = ecr_repo.registry_id.apply(_get_registry_info)

image = docker.Image(
    "my_app:image",
    build=docker.DockerBuildArgs(
        context=str(PROJECT_DIR),
        dockerfile=str(PROJECT_DIR / "Dockerfile"),
        platform="linux/amd64",
        target="prod",
        # BREAKS START
        cache_from=docker.CacheFromArgs(images=[pulumi.Output.concat(ecr_repo.repository_url, ":latest")])
        # BREAKS END
    ),
    registry=registry,
    image_name=pulumi.Output.concat(ecr_repo.repository_url, "my_app:latest"),
    skip_push=True,
)
```

`Dockerfile`:
```Dockerfile
FROM python:3.9-slim-bullseye as base

RUN echo "The Dockerfile contents are irrelevant"
```

### Output of `pulumi about`

```
CLI          
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.33.0
docker      4.1.1

Host     
OS       darwin
Version  13.2.1
Arch     x86_64
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by guineveresaenger**
In #555 we addressed a panic for an empty `cacheFrom` object.
We added a verificaton step at the Check() function to fail early.
This introduced a panic created by passing unknowns to marshalCachedImages.
This pull request refines the logic in the marshalling function to handle unknowns, catches possible panics via returning a helpful error, and adds tests for these additional scenarios.
Fixes #576.

- Improve error messaging for input verification when called during Check() Move verification to its own if block
- Add tests to verify cacheFrom marshaling

### CODE REVIEW

File: provider/provider.go [hunk 1]
```diff
@@ -195,8 +194,10 @@ func (p *dockerNativeProvider) Check(ctx context.Context, req *rpc.CheckRequest)
 			}
 		}
 
-		if _, err := marshalCachedImages(inputs["build"]); err != nil {
-			err = p.host.Log(ctx, diag.Error, urn, msg)
+	}
+	if _, err = marshalCachedImages(inputs["build"]); err != nil {
+
+		if err != nil {
```
Comment (iwahbe) [inline provider/provider.go:200]: It looks like we have an extra `err != nil` here.

File: provider/image.go [hunk 2]
```diff
@@ -419,10 +419,18 @@ func marshalCachedImages(b resource.PropertyValue) ([]string, error) {
 	// if we specify a list of stages, then we only pull those
 	cacheFrom := c.ObjectValue()
 	if cacheFrom["images"].IsNull() {
-		return cacheImages, fmt.Errorf("if you want to use cacheFrom, you must have `images` set")
+		return cacheImages, fmt.Errorf("cacheFrom requires an `images` field")
```
Comment (iwahbe) [inline provider/image.go:422]: What happens if `cacheFrom` is known but `cacheFrom["images"]` is unknown in preview?

Essentially, I can't find this test case:
```go
	t.Run("Test Cached Images Passes On Unknowns", func(t *testing.T) {
		expected := []string(nil)
		buildInput := resource.NewObjectProperty(resource.PropertyMap{
			"cacheFrom": resource.NewObjectProperty(resource.PropertyMap{
				"images": resource.NewNullProperty(), // unknowns are passed as null property values
			}),
		})
		actual, err := marshalCachedImages(buildInput)
		assert.NoError(t, err)
		assert.Equal(t, expected, actual)
	})
```

**Review by iwahbe — APPROVED** [review]
Thanks for all the testing! From first glance, it looks like we missed a corner case, but otherwise LGTM!

File: provider/image.go [hunk 3]
```diff
@@ -418,11 +418,22 @@ func marshalCachedImages(b resource.PropertyValue) ([]string, error) {
 
 	// if we specify a list of stages, then we only pull those
 	cacheFrom := c.ObjectValue()
+	if _, ok := cacheFrom["images"]; !ok {
```
Comment (jazzyfresh) [inline provider/image.go:421]: possibly unnecessary optimization, but could we assign `cacheFrom["images"]` to a named var to it can be reused below?

File: provider/image.go [hunk 4]
```diff
@@ -418,11 +418,22 @@ func marshalCachedImages(b resource.PropertyValue) ([]string, error) {
...
+		return cacheImages, fmt.Errorf("cacheFrom requires an `images` field")
+	}
 	if cacheFrom["images"].IsNull() {
-		return cacheImages, fmt.Errorf("if you want to use cacheFrom, you must have `images` set")
```
Comment (jazzyfresh) [inline provider/image.go:422]: i'm a bit confused about the distinction here between the `cacheFrom["images"]` property being unset as in the prior if-statement check, and here where it could be set but it's a Null type value. would it be an error in both cases? please correct my misunderstanding

File: provider/image.go (hunk 2 above)
Comment (guineveresaenger) [reply provider/image.go:422]: Nice catch! I changed it to traditional key presence checking, and return nil on an unknown field.

Comment (guineveresaenger) [reply provider/image.go:422]: Nice catch! I changed it to traditional key presence checking, and return nil on an unknown field.

Comment (guineveresaenger) [reply provider/image.go:422]: Nice catch! I changed it to traditional key presence checking, and return nil on an unknown field.

**Review by jazzyfresh — APPROVED** [review]
Great tests!

File: provider/image.go (hunk 4 above)
Comment (guineveresaenger) [reply provider/image.go:422]: yeah! so the first check asks "did you set this field? if you haven't, we'll error out and ask you to set it"
the second check says "is the _value_ of `images` null; if so, we need to allow it because it may be an unknown" - this covers the use case where a list may be passed in from another resource output.
Prior to adding this verification to `Check()`, we didn't need to worry about this, because we only called this function from Create(), and Create handles unknowns differently.
I like the early verification, though.

File: provider/image.go (hunk 3 above)
Comment (guineveresaenger) [reply provider/image.go]: I like it, thank you! :)
